DEATH_MESSAGES = ["	Not peaking at ten.	"	,
"	Eating a whole bucket of fried chicken.	"	,
"	Finding true love.	"	,
"	Voting for the wrong guy.	"	,
"	Riding a bus.	"	,
"	Learning from the fatal mistake you just made.	"	,
"	First chest hair.	"	,
"	First speeding ticket.	"	,
"	Eating a meal directly from the can.	"	,
"	Not failing.	"	,
"	Winning the lottery (but let's face it, that was pretty unlikely anyhow).	"	,
"	Graduating high school.	"	,
"Accomplishing your dreams. (Unless your dream was dying alone in a mansion,
in which case - good job.)	"	,
"	Sharing your first kiss.	"	,
"	Going to an awkward high school reunion.	"	,
"	Complaining about how life used to be better, and kids these days 'just
don't get it.'	"	,
"	Figuring out where your uncle is.	"	,
"	Wearing sweatpants for 4 weeks straight.	"	,
"	Finding that perfect ironic t-shirt.	"	,
"	Defaulting on a mortgage.	"	,
"	Lying about your weight (to others).	"	,
"	Lying about your weight (to yourself).	"	,
"	Growing beyond 4'0'.	"	,
"	Realizing that canned whipped cream is, indeed, a meal.	"	,
"Being better at this sort of thing than you are right now. Actually, being
better at absolutely anything than you are RIGHT NOW. Or, were.	"	,
"	Calling in 'sick.'	"	,
"	Something really neat that you don't even know about, because you're dead.	"	,
"	Getting to da choppa.	"	,
"	Learning to whittle.	"	,
"	Earning, then ignoring, the right to vote.	"	,
"	Learning to whistle.	"	,
"	Learning to read (we can assume).	"	,
"	Learning to ride a bike (hey, based on your skill here, I'm just assuming).	"	,
"Writing a college entrance essay and desperately hoping you're as good as
45,000 other applicants.	"	,
"	Having a beard.	"	,
"	Accidentally hitting 'Reply: All.'	"	,
"Watching your favorite childhood TV shows getting turned into horrible
movies."	,
"	Getting past this level with one less death.	"	,
"	Getting caught using a fake ID.	"	,
"	Discovering that good friends are what life's all about.	"	,
"	Outliving... oh, just about anything.	"	,
"	Learning to identify things that will, in fact, kill you.	"	,
"	Becoming disillusioned with life.	"	,
"	Having a vocabulary of more than ten words.	"	,
"	Getting old enough to... wait... Hold on, I'll remember it...	"	,
"	Backpacking through Europe.	"	,
"	Eating two entire cakes.	"	,
"	Gazing at the stars and getting that 'really small' feeling.	"	,
"	Building a mansion that some kid gets stuck in.	"	,
"	Looking back on this and laughing.	"	,
"	First awkward date.	"	,
"	The ridiculous price of college tuition in seven years (seriously, for a
state school it'll be like $95,000)."	,
"	Shaving a beard.	"	,
"	Winning the Kentucky Derby.	"	,
"	Outgrowing a favorite sweater.	"	,
"	Going to graduate school to avoid the real world.	"	,
"	Mistaking wasabi for guacamole.	"	,
"	Seeing an R rated film.	"	,
"	Doing Vegas.	"	,
"	Forgetting where you put your keys.	"	,
"	Pretending to enjoy classical music.	"	,
"	Keeping up with current events just so you know what to be outraged about.	"	,
"	Moving out.	"	,
"	Riding a dinosaur.	"	,
"	Preferably, improving your reflexes.	"	,
"	Judging others for their choice of transportation.	"	,
"	Judging others based on income.	"	,
"	Purchasing flat-packed plywood furniture.	"	,
"	Awkwardly ignoring a person holding a petition.	"	,
"	Realizing you're horribly out of style.	"	,
"	First tax audit.	"	,
"	Putting the empty milk carton right back in the fridge.	"	,
"	Watching something you experienced the first time become retro.	"	,
"	Discovering what's in the safe.	"	,
"	Welcoming our robot overlords (just covering all contingencies).	"	,
"	Being marginally successful at paying your bills on time.	"	,
"	Learning to drive.	"	,
"	Getting over a bad haircut.	"	,
"	The itchy stubble of trying - but failing - to grow a beard.	"	,
"	Getting a divorce.	"	,
"	Shaving a llama.	"	,
"	Realizing that you are 40 and alone and really need to get out more.	"	,
"	Writing a series of depressing comments for a video game.	"	,
"	Telling all your friends about 'that one time I didn't die in a mansion.'	"	,
"	Lying on your taxes (but only a little bit.)	"	,
"	Growing old enough to realize that you are not special.	"	,
"	Feeling the crisp air of a new spring day.	"	,
"	Having a mid-life crisis.	"	,
"	Getting married.	"	,
"	Stating that 'the book was better than the film.'	"	,
"	Your first overdraft fee.	"	,
"	Being able to reach the sink.	"	,
"	Employing your first housekeeper.	"	,
"	Firing your first housekeeper.	"	,
"	Hearing your favorite song become elevator music.	"	,
"	Learning to follow safety instructions.	"	,
"	Learning the difference between Tall, Venti, and Grande.	"	,
"	Falling in love.	"	,
"	Your first car.	"	,
"	Forgetting an anniversary.	"	,
"	Crashing the family car.	"	,
"	Live long enough to complain about the lack of flying cars.	"	,
"	Avoiding the dentist.	"	,
"	Rising auto insurance premiums purely based on geographic zoning.	"	,
"	Rediscovering your childhood (one that doesn't involve being dead).	"	,
"	Changing your major in college for the third time.	"	,
"	Buying a house.	"	,
"	Accomplishing your dreams.	"	,
"	Failing your way into middle management.	"	,
"	Finding yourself.	"	,
"	Being angry that your parents 'just don't understand.'	"	,
"	Eating cereal for breakfast, lunch, and dinner for months on end.	"	,
"	Waiting for the cable guy.	"	,
"	Willingly accepting an unpaid internship.	"	,
"	Watching those cable channels you're not supposed to see.	"	,
"Finding out what's beyond the next door (because it's really cool, and you
don't get to know now).	"	,
"	Complaining about public schools.	"	,
"	Complaining about politics you only vaguely understand.	"	,
"	Eating ramen for three months straight.	"	,
"	Feeling bad about not going outside... but not leaving the house anyways.	"	,
"	Feeling the sting of going dateless to the Prom.	"	,
"	Becoming nostalgic about things that were only mediocre at best.	"	,
"	Using a fake ID.	"	,
"	The social pressure of knowing which bands are right to like.	"	,
"	Socks with sandals.	"	,
"	Having your wisdom teeth pulled.	"	,
"	Correcting the mistakes that got you here.	"	,
"	Eating an entire cake.	"	,
"	The zombie apocalypse (maybe this is for the best).	"	,
"	Denying a homeless person the spare change that you really do have.	"	,
"Eventually dying of unrelated causes many, many years from now, content in
your old age."		,]
