a=0
splashtext[a]="Right, very carefully, slower than molasses drips off a spoon. :)"
//a+=1;splashtext[a]=""
a+=1;splashtext[a]="I'm an orphan, but I have a dog!"
a+=1;splashtext[a]="When it's L-...purple, like the evening,# of a spring evening, then it means he's okay."
a+=1;splashtext[a]="I'm always squeezing the trigger! Should I not be do that-? …doing that?"
a+=1;splashtext[a]="It's all- this is all mechanically necessary!"
a+=1;splashtext[a]="They don't- There's no article about that on Wikipedia, the free encyclopedia!"
a+=1;splashtext[a]="I drink soda for lunch!"
a+=1;splashtext[a]="Mr. Kid! Be careful! More careful... #than a badger going after a... a den of snakes!"
a+=1;splashtext[a]="Black Mesa makes ALL the Powerade™!"
a+=1;splashtext[a]="This is all instinct, Mr. Kid! I'm scared!"
a+=1;splashtext[a]="I can recognize Beyblades when I see 'em!"
a+=1;splashtext[a]="Yup! And it's all built to code. The U.S. lets us do this. #This is all to regulation. Everything."
a+=1;splashtext[a]="This is all built to CODE!! It'll be okay."
a+=1;splashtext[a]="Grab a soda, Mr. Kid! It'll help you see faster!"
a+=1;splashtext[a]="When we get outta here I'm gonna write #the Wikipedia article for the the uh the Sunkist kidnapping!"
a+=1;splashtext[a]="OH MY GOD WE'RE DOOOMMMEDD"
a+=1;splashtext[a]="The perfect dog..."
a+=1;splashtext[a]="Sbarros tommorow, quiznos today!"
a+=1;splashtext[a]="I read about it on Wikipedia, the FREE online encyclopedia that ANYONE can edit!"
a+=1;splashtext[a]="DON'T MESS WITH THE SCIENNCEE TEAMMM"
a+=1;splashtext[a]="He's the perfect dog..."
a+=1;splashtext[a]="Green means he's not mean! b-but maybe not here, Mr. Kid."
a+=1;splashtext[a]="Green, to blue... that means it's nice to meet you!"
a+=1;splashtext[a]="They have barrels just like we do!"
a+=1;splashtext[a]="This is what OSHA was trying to warn us about!"
a+=1;splashtext[a]="I heard Blu-ray is better than DVD!"
a+=1;splashtext[a]="Sunkist lives forever!!! I was just worried that that would like, trick..?"
a+=1;splashtext[a]="Big dogs are better!"

return splashtext[irandom_range(0, a)]
