splashtext[0]="Right, very carefully, slower than molasses drips off a spoon. :)"
splashtext[1]="I'm an orphan, but I have a dog!"
splashtext[2]="When it's L-...purple, like the evening,# of a spring evening, then it means he's okay."
splashtext[3]="I'm always squeezing the trigger! Should I not be do that-? …doing that?"
splashtext[4]="It's all- this is all mechanically necessary!"
splashtext[5]="They don't- There's no article about that on Wikipedia, the free encyclopedia!"
splashtext[6]="I drink soda for lunch!"
splashtext[7]="Mr. Kid! Be careful! More careful... #than a badger going after a... a den of snakes!"
splashtext[8]="Black Mesa makes ALL the Powerade™!"
splashtext[9]="This is all instinct, Mr. Kid! I'm scared!"
splashtext[10]="I can recognize Beyblades when I see 'em!"
splashtext[11]="Yup! And it's all built to code. The U.S. lets us do this. This is all to regulation. Everything."
splashtext[12]="This is all built to CODE!! It'll be okay."
splashtext[13]="Grab a soda, Mr. Kid! It'll help you see faster!"
splashtext[14]="When we get outta here I'm gonna write #the Wikipedia article for the the uh the Black Mesa Golem Ape!"
splashtext[15]="OH MY GOD WE'RE DOOOMMMEDD"
splashtext[16]="The perfect dog..."
splashtext[17]="Sbarros tommorow, quiznos today!"
splashtext[18]="I read about it on Wikipedia, the FREE online encyclopedia that ANYONE can edit!"
splashtext[19]="DON'T MESS WITH THE SCIENNCEE TEAMMM"
splashtext[20]="Bye, hi... sigh Hawaii"
splashtext[21]="Jesse Jesse Jesse, can't you see, you're little cellphones a ring-ringin'"

return splashtext[irandom_range(0, 20)]
